server.port: ${host.environment.port:8761}

eureka:
  instance:
    hostname: ${spring.application.name:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${spring.application.name}:${server.port}/eureka/
